spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: accountUser
          uri: lb://account-service
          predicates:
            - Path=/users/**
        - id: accountAuthenticate
          uri: lb://account-service
          predicates:
            - Path=/authenticate

server:
  port: 8087

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka

auth:
  whitelisted-path:
    - /authenticate
