spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: accountModule
          uri: lb://account-service
          predicates:
            - Path=/users/**

server:
  port: 8085

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
